language: node_js
node_js:
- '0.10.36'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
- bower install
- brunch b
script:
- ./run_tests.sh
notifications:
  slack:
    secure: gcPvQOCwtvw4nUm9PaR5ztgGsXOdNB0MGNshhLkgX/TXAJUWj+6BgrrWi5NkptaOMrvM+2MrDDHW1XqSx2WOpS334EIYIW1gG82QByY9lR5hC9Id4Gqd3BT9Dl9eo3ev5nA1ffMXvgXGgP/VMd7Xjn/OC1iYNCud8dGPSDdzG5s=
